CFLAGS=-Wall -g


 TARGET = ex1 ex2 ex3 ex4 \
 		  ex5 ex6 ex7 ex8 \
		  ex9 ex10

#all: ex1 ex2 ex3
all: ${TARGET}
#	echo $^

#${TARGET} : ${TARGET}.c
#	cc ${CFLAGS} ${TARGET}

clean:
	#rm -f ex1 ex2 ex3
	rm -f ${TARGET}


